- name: KommuAssist2
  category: Device
  prices:
    MYR: 1.00
    USD: 1.00
  subscription:
    id: plan_QyljeG4K1bOoHG
    name: Rent-to-Own
    month: 36
    monthly_price:
      MYR: 2.00

- name: Sim Card
  category: Add-on
  prices:
    MYR: 28.90

- name: Harness Set
  prices:
    MYR: 320.00
    USD: 120.00  
  category: Hardware
  image: /img/products/accessories/sample.png
  description: Mount to setup KA2 device onto windshield...
  includes:
  - ADAS Relay
  - ADAS Connector
  - 2x USB-C
  - OBD Power
  - Mount with adhesive
  - Electrostatic sticker

  dropdown:
    title: Select car model
    placeholder: Car model
    source: "https://raw.githubusercontent.com/kommuai/bukapilot/snapshot/selfdrive/car/supported_vehicle.json"
    list_key: "standard"
    value_template: "{{brand}} {{model}} {{year}} {{variant}}"

- name: KA2 Mount
  prices:
    MYR: 50.00
    USD: 10.00
  category: Hardware
  image: /img/products/accessories/sample.png
  description: Mount to setup KA2 device onto windshield...
  includes:
  - Mount with adhesive
  - Electrostatic sticker
  - Alcohol wipes
  dropdown:
    title: Select car model
    placeholder: Car model
    source: "https://raw.githubusercontent.com/kommuai/bukapilot/snapshot/selfdrive/car/supported_vehicle.json"
    list_key: "standard"
    value_template: "{{brand}} {{model}} {{year}} {{variant}}"

- name: nanoSIM card
  prices:
    MYR: 10.00
    USD: 10.00
  category: Others
  image: /img/products/accessories/sample.png
  description: Mount to setup KA2 device onto windshield...
  includes:
  - U-mobile prepaid SIM card

- name: microSD card
  prices:
    MYR: 30.00
    USD: 30.00
  category: Others
  image: /img/products/accessories/sample.png
  description: Mount to setup KA2 device onto windshield...
  includes:
  - 64gb microSD card
  
- name: ADAS Connector
  prices:
    MYR: 150.00
    USD: 12.00
  category: Cables & connectors
  image: /img/products/accessories/sample.png
  description: Mount to setup KA2 device onto windshield...
  includes:
  - ADAS Connector
  dropdown:
    title: Select car model
    placeholder: Car model
    source: "https://raw.githubusercontent.com/kommuai/bukapilot/snapshot/selfdrive/car/supported_vehicle.json"
    list_key: "standard"
    value_template: "{{brand}} {{model}} {{year}} {{variant}}"

- name: Short USB 3.1 Type-C Cable
  prices:
    MYR: 30.00
    USD: 33.00
  category: Cables & connectors
  image: /img/products/accessories/sample.png
  description: To connect Vision to car ADAS system
  includes:
  - Relay-to-Vision USB-C Cable

- name: Long USB 3.1 Type-C Cable
  prices:
    MYR: 40.00
    USD: 33.00
  category: Cables & connectors
  image: /img/products/accessories/sample.png
  description: To connect Vision to car ADAS system
  includes:
  - OBD-to-Relay USB-C Cable

- name: OBD Connector
  prices:
    MYR: 100.00
    USD: 33.00
  category: Cables & connectors
  image: /img/products/accessories/sample.png
  description: To connect Vision to car ADAS system
  includes:
  - OBD connector

- name: ADAS Relay
  prices:
    MYR: 150.00
    USD: 33.00
  category: Hardware
  image: /img/products/accessories/sample.png
  description: To connect Vision to car ADAS system
  includes:
  - ADAS Relay

