- name: KommuAssist2
  category: Device
  prices:
    MYR: 3999.00
    USD: 949.00


- name: Harness Set
  prices:
    MYR: 129.00
    USD: 29.00  
  category: Hardware
  image: /img/products/accessories/sample.png
  description: Mount to setup KA2 device onto windshield...
  includes:
  - Mount with adhesive
  - Electrostatic sticker
  - Alcohol wipes

- name: KA2 Mount
  prices:
    MYR: 29.00
    USD: 9.00
  category: Hardware
  image: /img/products/accessories/sample.png
  description: Mount to setup KA2 device onto windshield...
  includes:
  - Mount with adhesive
  - Electrostatic sticker
  - Alcohol wipes

- name: T Shirt
  prices:
    MYR: 1290.00
    USD: 329.00
  category: Others
  image: /img/products/accessories/sample.png
  description: Mount to setup KA2 device onto windshield...
  includes:
  - Mount with adhesive
  - Electrostatic sticker
  - Alcohol wipes
  
- name: Harness Set
  prices:
    MYR: 129.00
    USD: 29.00
  category: Cables & connectors
  image: /img/products/accessories/sample.png
  description: Mount to setup KA2 device onto windshield...
  includes:
  - Mount with adhesive
  - Electrostatic sticker
  - Alcohol wipes

  
- name: Harness Set
  prices:
    MYR: 129.00
    USD: 29.00
  category: Others
  image: /img/products/accessories/sample.png
  description: Mount to setup KA2 device onto windshield...
  includes:
  - Mount with adhesive
  - Electrostatic sticker
  - Alcohol wipes

- name: Harness Set
  prices:
    MYR: 129.00
    USD: 29.00
  category: Others
  image: /img/products/accessories/sample.png
  description: Mount to setup KA2 device onto windshield...
  includes:
  - Mount with adhesive
  - Electrostatic sticker
  - Alcohol wipes