- name: KommuAssist2
  category: Device
  prices:
    MYR: 1.00
    USD: 1.00



- name: Harness Set
  prices:
    MYR: 1.00
    USD: 1.00  
  category: Hardware
  image: /img/products/accessories/sample.png
  description: Mount to setup KA2 device onto windshield...
  includes:
  - Mount with adhesive
  - Electrostatic sticker
  - Alcohol wipes
  dropdown:
    title: Select Harness
    source: "https://raw.githubusercontent.com/kommuai/bukapilot/snapshot/selfdrive/car/supported_vehicle.json"
    list_key: "standard"
    value_template: "{{brand}} {{model}} {{year}} {{variant}}"

- name: KA2 Mount
  prices:
    MYR: 1.00
    USD: 1.00
  category: Hardware
  image: /img/products/accessories/sample.png
  description: Mount to setup KA2 device onto windshield...
  includes:
  - Mount with adhesive
  - Electrostatic sticker
  - Alcohol wipes

- name: T Shirt
  prices:
    MYR: 1.00
    USD: 1.00
  category: Others
  image: /img/products/accessories/sample.png
  description: Mount to setup KA2 device onto windshield...
  includes:
  - Mount with adhesive
  - Electrostatic sticker
  - Alcohol wipes
  
- name: Harness Set
  prices:
    MYR: 1.00
    USD: 1.00
  category: Cables & connectors
  image: /img/products/accessories/sample.png
  description: Mount to setup KA2 device onto windshield...
  includes:
  - Mount with adhesive
  - Electrostatic sticker
  - Alcohol wipes

  
- name: Harness Set
  prices:
    MYR: 1.00
    USD: 1.00
  category: Others
  image: /img/products/accessories/sample.png
  description: Mount to setup KA2 device onto windshield...
  includes:
  - Mount with adhesive
  - Electrostatic sticker
  - Alcohol wipes

- name: Harness Set
  prices:
    MYR: 1.00
    USD: 1.00
  category: Others
  image: /img/products/accessories/sample.png
  description: Mount to setup KA2 device onto windshield...
  includes:
  - Mount with adhesive
  - Electrostatic sticker
  - Alcohol wipes